[package]
name = "lapis/player-data-example"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
private = true

[dependencies]
t = "osyrisrblx/t@3.0.0"
Promise = "evaera/promise@4.0.0"
